-- ==================================================
-- MÉTRICAS PRIVADAS PARA O SITE MELISSA YUMI OKUNO
-- Execute este arquivo uma única vez no SQL Editor do Supabase.
-- ==================================================

create table if not exists public.site_visitors (
  visitor_id uuid primary key,
  created_at timestamptz not null default now(),
  last_visit timestamptz not null default now(),
  visit_count bigint not null default 1 check (visit_count >= 1)
);

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'whatsapp_click')),
  visitor_id uuid not null,
  page text not null default '/',
  source text,
  service text,
  created_at timestamptz not null default now()
);

create index if not exists site_events_type_created_at_idx on public.site_events (event_type, created_at desc);
create index if not exists site_events_service_idx on public.site_events (service) where service is not null;

-- RLS permanece ativado. Não criamos políticas diretas para anon/authenticated:
-- o navegador só pode usar as funções específicas liberadas mais abaixo.
alter table public.site_visitors enable row level security;
alter table public.site_events enable row level security;
revoke all on table public.site_visitors from anon, authenticated;
revoke all on table public.site_events from anon, authenticated;

-- Registra uma visualização, atualiza o navegador visitante e devolve totais públicos.
create or replace function public.record_page_view(p_visitor_id uuid, p_page text default '/')
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  safe_page text := left(coalesce(nullif(p_page, ''), '/'), 200);
  result jsonb;
begin
  if p_visitor_id is null then
    raise exception 'visitor_id is required';
  end if;

  insert into public.site_visitors (visitor_id)
  values (p_visitor_id)
  on conflict (visitor_id) do update
    set last_visit = now(),
        visit_count = public.site_visitors.visit_count + 1;

  insert into public.site_events (event_type, visitor_id, page)
  values ('page_view', p_visitor_id, safe_page);

  select jsonb_build_object(
    'total_views', (select count(*) from public.site_events where event_type = 'page_view'),
    'approx_visitors', (select count(*) from public.site_visitors)
  ) into result;

  return result;
end;
$$;

-- Registra apenas o início de um clique para o WhatsApp, sem conteúdo de conversa.
create or replace function public.record_whatsapp_click(
  p_visitor_id uuid,
  p_page text default '/',
  p_source text default 'desconhecido',
  p_service text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_visitor_id is null then
    raise exception 'visitor_id is required';
  end if;

  insert into public.site_events (event_type, visitor_id, page, source, service)
  values (
    'whatsapp_click',
    p_visitor_id,
    left(coalesce(nullif(p_page, ''), '/'), 200),
    left(coalesce(nullif(p_source, ''), 'desconhecido'), 80),
    left(nullif(p_service, ''), 80)
  );

  return jsonb_build_object('ok', true);
end;
$$;

-- Remove a permissão padrão e libera somente estas operações controladas.
revoke all on function public.record_page_view(uuid, text) from public;
revoke all on function public.record_whatsapp_click(uuid, text, text, text) from public;
grant execute on function public.record_page_view(uuid, text) to anon, authenticated;
grant execute on function public.record_whatsapp_click(uuid, text, text, text) to anon, authenticated;
